FROM rhub/r-minimal:4.1

RUN installr -d \
    -a "freetype fontconfig-dev fontconfig cairo-dev" \
    -t "zlib-dev gfortran libcurl curl-dev libxt-dev" \
    data.table dplyr ggplot2 \
    knitr rstudio/rmarkdown tidyr \
    tibble purrr BiocManager \
    circlize plotly RColorBrewer \
    stringr bit64 Cairo \
    scales jsonlite htmltools \
    fontawesome glin/reactable crosstalk \
    svglite jokergoo/ComplexHeatmap
    
RUN wget https://github.com/jgm/pandoc/releases/download/2.13/pandoc-2.13-linux-amd64.tar.gz && \
    tar xzf pandoc-2.13-linux-amd64.tar.gz && \
    mv pandoc-2.13/bin/* /usr/local/bin/ && \
    rm -rf pandoc-2.13*

ADD R/ /R/

WORKDIR /data