jobs:
  build:
    machine:
        java:
          version: oraclejdk8
        services:
          - docker
    steps:
      - checkout
      - run:
          name: Setup environment
          command: |
            curl -fsSL get.nextflow.io | bash
            nextflow pull -hub github jimmyliu1326/SamnSero_Nextflow
      - run:
          name: Run Tests
          command: |
            nextflow run jimmyliu1326/SamnSero_Nextflow --help