source(file.path(src_dir, "src/samnsero_ggplot.R"))
cc_ly <- checkm_plot(data)
quast_ly <- quast_plot(data)
if (rt) {
	target_bases_ly <- temporal_plot(tp_SharedData, y = "target_bases", axis.y.text = "Target DNA", axis.y.title = "Target DNA (Mbps)", axis.y.text.suffix = ' Mbps', height = 250)
	target_count_ly <- temporal_plot(tp_SharedData, y = "target_count", axis.y.text = "Target DNA", axis.y.title = "Target DNA (K reads)", axis.y.text.suffix = ' K', height = 250)
	total_bases_ly <- temporal_plot(tp_SharedData, y = "total_bases", axis.y.text = "Total DNA", axis.y.title = "Total DNA (Mbps)", axis.y.text.suffix = ' Mbps', height = 250)
	total_count_ly <- temporal_plot(tp_SharedData, y = "total", axis.y.text = "Total DNA", axis.y.title = "Total DNA (K reads)", axis.y.text.suffix = ' K', height = 250)
	n50_ly <- temporal_plot(tp_SharedData, y = "N50", axis.y.text = "N50", axis.y.title = "N50 (Mbps)", axis.y.text.suffix = ' Mbps')
	length_ly <- temporal_plot(tp_SharedData, y = "Total length", axis.y.text = "Size", axis.y.title = "Assembly size (Mbps)", axis.y.text.suffix = ' Mbps')
	completeness_ly <- temporal_plot(tp_SharedData, y = "Completeness", axis.y.text = "Completeness", axis.y.title = "Completeness (%)", axis.y.text.suffix = '%', height = 250)
	contamination_ly <- temporal_plot(tp_SharedData, y = "Contamination", axis.y.text = "Contamination", axis.y.title = "Contamination (%)", axis.y.text.suffix = '%', height = 250)
	heterogeneity_ly <- temporal_plot(tp_SharedData, y = "Strain heterogeneity", axis.y.text = "Heterogeneity", axis.y.title = "Strain heterogeneity (%)", axis.y.text.suffix = '%', height = 250)
	contigs_ly <- temporal_plot(tp_SharedData, y = "# contigs", axis.y.text = "# contigs", axis.y.title = "Number of contigs")
	depth_ly <- temporal_plot(tp_SharedData, y = "Avg. coverage depth", axis.y.text = "Coverage", axis.y.title = "Depth of Coverage", axis.y.text.suffix = 'x')
	bacteria_ly <- temporal_plot(tp_SharedData, y = "bacteria", axis.y.text = "Proportion", axis.y.title = "<b>Bacterial</b> reads (%)", axis.y.text.suffix = '%')
	virus_ly <- temporal_plot(tp_SharedData, y = "virus", axis.y.text = "Proportion", axis.y.title = "<b>Viral</b> reads (%)", axis.y.text.suffix = '%')
	archaea_ly <- temporal_plot(tp_SharedData, y = "archaea", axis.y.text = "Proportion", axis.y.title = "<b>Archaeal</b> reads (%)", axis.y.text.suffix = '%')
	eukaryota_ly <- temporal_plot(tp_SharedData, y = "eukaryota", axis.y.text = "Proportion", axis.y.title = "<b>Eukaryotic</b> reads (%)", axis.y.text.suffix = '%')
	artificial_ly <- temporal_plot(tp_SharedData, y = "artificial", axis.y.text = "Proportion", axis.y.title = "<b>Artificial</b> reads (%)", axis.y.text.suffix = '%')
}
