source(file.path(src_dir, "src/reactable-helper.R"))
source(file.path(src_dir, "src/samnsero_annot_rtbl.R"))
amr_tbl <- amr_reactable(amr_data)
vf_tbl <- vf_reactable(vf_data)
plasmid_tbl <- plasmid_reactable(plasmid_data)