source(file.path(src_dir, "src/samnsero_summary.R"))
tidy_res <- annot_sum2mat(annot_summary)
amr_drug_summary <- amr_class_sum(amr_res_clean)
plasmid_summary <- getSummaryType("Plasmid")
amr_summary <- getSummaryType("AMR")
vf_summary <- getSummaryType("Virulence Factor")