---
title: "SamnSero Annotation Report"
date: "`r date()`"
output: html_document
---

```{r setup, include=FALSE}
# global opts
knitr::opts_chunk$set(echo = F, message = F, warning = F)
```

```{r source}
source("samnsero_load.R")
source("abricate_plot.R")
library(gt)
```

```{r parse-args}
args <- commandArgs(trailingOnly = T)
sistr_path <- args[1]
annot_dir <- args[2]
annot_path <- list.files(annot_dir, pattern = "summary.tab")
annot_name <- map_chr(annot_path, ~unlist(str_split(., "_summary"))[1])
annot_name <- case_when(annot_name == "card" ~ "AMR Gene",
												annot_name == "vfdb" ~ "Virulence Factor",
												annot_name == "plasmidfinder" ~ "Plasmid",
												T ~ annot_name)
```

```{r check-file}
# check if abricate result is empty (containing only header)
valid <- map_lgl(annot_path, function(x) {
	file <- readLines(file.path(annot_dir, x))
	if (length(file) == 1) { return(F) } else { return(T) }
})
annot_path <- annot_path[valid]
annot_name <- annot_name[valid]
```

```{r load-data}
# read sistr output
sistr_res <- load_sistr(sistr_path)
# read abricate outputs
annot_res <- map2(annot_name, annot_path, function(x, y) {
	load_abricate_summary(file.path(annot_dir, y)) %>% 
		select(-NUM_FOUND) %>% 
		mutate_at(vars(2:ncol(.)), ~as.character(.))
})
```

```{r clean-abricate}
# combine list of df to one df
aggregate_res <- map(annot_res, ~pivot_longer(., cols = 2:ncol(.),
																							names_to = "element",
																							values_to = "identity"))
# get annotation type of each element
annot_types <- map2_dfr(annot_name, aggregate_res, function(x, y) {
	y %>% 
		mutate(type = x) %>% 
		select(element, type) %>% 
		distinct()
}) %>%
	mutate(type = factor(type,
						levels = annot_name))
```

```{r check-duplicates}
dups <- annot_types %>% 
	group_by(element) %>% 
	tally() %>% 
	filter(n > 1) %>% 
	pull(element)

if (length(dups) > 0) {
	message("Duplicated annotation identifier detected..")
	message("The following hits are found in multiple databases: ", str_c(dups, ", "))
	quit(status = 1)
}
```


```{r clean-sistr}
# mask unresolved serotypes
sistr_res <- sistr_res %>% 
	mutate(serovar = if_else(str_detect(serovar, "|"), "Unresolved", serovar))
```

<br>

<br>

```{r summary}
aggregate_res %>% 
	bind_rows() %>% 
	left_join(sistr_res, by = "id") %>% 
	left_join(annot_types, by = "element") %>% 
	filter(identity != ".") %>% 
	group_by(id, serovar, type, .drop = F) %>% 
	tally() %>% 
	ungroup() %>% 
	pivot_wider(names_from = "type",
							values_from = "n") %>% 
	mutate_if(is.numeric, ~ifelse(is.na(.), 0, .)) %>% 
	gt(rowname_col = "id") %>% 
	gt::cols_label(serovar = md("Predicted<br>Serovar")) %>% 
	tab_style(
		style = cell_text(
			weight = "bold",
			font = "arial"
		),
		locations = cells_stub(everything())
	) %>% 
	tab_style(
		style = cell_text(
			color = "#444",
			font = "arial"
		),
		locations = cells_column_labels(everything())
	) %>% 
	tab_header(
		title = md("Functional annotations of input *Salmonella* genomes"),
		subtitle = md("Genes found in multiple copies are reported more than once in the summary table")
	) %>% 
	# tab_footnote(
	# 	footnote = "Antimicrobial resistance: only AMR genes are detected,
	# 							mutations that confer resistance are not reported",
	# 	locations = cells_column_labels(2)) %>% 
	# tab_footnote(
	# 	footnote = "Virulence factor",
	# 	locations = cells_column_labels(3)
	# ) %>% 
	grand_summary_rows(
		columns = annot_name,
		fns = list(Average = "mean")
	)
```


```{r df2matrix}
tidy_res <- annot_res %>% 
	reduce(left_join, by = "id") %>% 
	column_to_rownames("id") %>% 
	t() %>%
	as.data.frame() %>% 
	rownames_to_column("id") %>% 
	mutate_at(vars(2:ncol(.)), ~ifelse(. == ".", 0, 1)) %>% 
	rowwise() %>% 
	mutate(var = var(c_across(2:ncol(.)))) %>% 
	filter(var != 0) %>% 
	select(-var) %>% 
	mutate_at(vars(2:ncol(.)), ~ifelse(. == 0, "A", "P")) %>% 
	column_to_rownames("id")
```

<br>

<br>

## Genome Annotation Presence/Absence Matrix
*Note: Only genetic elements with variable presence are shown.*

```{r plot-heatmap, fig.width=12, fig.height=12}
cell_w <- ncol(tidy_res)*0.12
cell_h <- nrow(tidy_res)*0.8
if (nrow(tidy_res != 0)) {
	plot_abricate(tidy_res, cell_w, cell_h, sistr_res)
} else {
	print("Heatmap was not plotted either because only a single sample was analyzed or no variable presence elements were found")
}

```




