---
title: "SamnSero QC Report"
date: "`r date()`"
output: html_document
---

```{r setup, include=FALSE}
# global opts
knitr::opts_chunk$set(echo = F, message = F, warning = F)
```

```{r source}
source("samnsero_load.R")
library(plotly)
library(ggplot2)
library(gt)
```

```{r parse-args}
args <- commandArgs(trailingOnly = T)
checkm_path <- args[1]
quast_path <- args[2]
sistr_path <- args[3]
```

```{r load-data}
# load data
checkm_res <- load_checkm(checkm_path)
quast_res <- load_quast(quast_path)
sistr_res <- load_sistr(sistr_path)
```

```{r combine-data}
combined_res <- quast_res %>%
 select(id, "# contigs", "Total length", "# N's per 100 kbp", "N50") %>%
 left_join(checkm_res %>%
 						select(id, Completeness, Contamination, "Strain heterogeneity") %>%
 						mutate(id = str_replace_all(id, "-", "_")),
 					by = "id") %>%
 left_join(sistr_res %>%
 						select(id, serovar, qc_status, qc_messages) %>%
 						mutate(id = str_replace_all(id, "-", "_")),
					by = "id"
 						) %>%
 select(id, serovar, qc_status,
 			 qc_messages, "Total length",
 			 Completeness, Contamination, 
 			 "Strain heterogeneity", everything()) %>%
 mutate(serovar = if_else(str_detect(serovar, "|"), "Unresolved", serovar))
```

```{r gt-col-helpers}
completeness_pal <- function(x) {
	high_q <- scales::col_numeric(
		palette = c("#F5736D", "#F6D57C", "#66C76B"),
		domain = c(80,100)
	)
	low_q <-  scales::col_numeric(
		palette = c("#F5736D","#F5736D"),
		domain = c(0, 80)
	)
	ifelse(x < 80, low_q(x), high_q(x))
}

contamination_pal <- function(x) {
	high_q <- scales::col_numeric(
		palette = c("#66C76B", "#F6D57C", "#F5736D"),
		domain = c(0,10)
	)
	low_q <-  scales::col_numeric(
		palette = c("#F5736D","#F5736D"),
		domain = c(10, 100)
	)
	ifelse(x > 10, low_q(x), high_q(x))
}

length_pal <- function(x) {
	high_q <- scales::col_numeric(
		palette = c("#66C76B", "#F6D57C", "#F5736D"),
		domain = c(4500000,6500000)
	)
	low_q <-  scales::col_numeric(
		palette = c("#F5736D","#F5736D"),
		domain = c(0, 4500000)
	)
	
	ifelse(x < 4500000, low_q(x), high_q(x))
}
```

<br>

<br>

### Quality metrics of input *Salmonella* assembled genomes

```{r plot-table}
combined_res %>% 
 gt(rowname_col = "id") %>% 
 	cols_label(serovar = "Predicted Serovar",
 						 `# N's per 100 kbp` = md("N's/100 kbp"),
						 qc_messages = md("SISTR QC Message(s)"),
 						 qc_status = md("SISTR<br>QC Status")) %>%
	cols_move_to_end(columns = "qc_messages") %>%
	tab_style(
		style = cell_text(
			weight = "bold",
			font = "arial"
		),
		locations = cells_stub(everything())
	) %>% 
	tab_style(
		style = cell_text(
			color = "#444",
			font = "arial"
		),
		locations = cells_column_labels(everything())
	) %>% 
 	data_color(
 		columns = 6,
 		colors = completeness_pal) %>%
 	data_color(
 		columns = 7,
 		colors = contamination_pal) %>%
 	data_color(
 			columns = 3,
 			colors = scales::col_factor(
		palette = c("#66C76B", "#F6D57C", "#F5736D"),
		domain=c("PASS", "WARNING", "FAIL"),
		levels=c("PASS", "WARNING", "FAIL"))) %>%
	data_color(
 			columns = 5,
 			colors = length_pal) %>%
 	gt::fmt_number(columns = c(5,11),
 						 decimals = 2,
 						 suffix = c("M", "M")) %>% 
	cols_width(
		"qc_messages" ~ px(3000),
		c("Completeness", "Contamination") ~ px(110),
		"Strain heterogeneity" ~ px(120),
		"id" ~ px(200),
		"Total length" ~ px(75),
		"qc_status" ~ px(85),
		"serovar" ~ px(100),
		"# contigs" ~ px(60),
		everything() ~ px(75)
  )
```

<br>

<br>

### Genome completeness and contamination evaluation

```{r checkm-viz, fig.width = 9, fig.height = 7}
p <- combined_res %>% 
 	ggplot(aes(x = Completeness, y = Contamination, fill = `Strain heterogeneity`, label = id, group = serovar)) +
 	geom_point() +
 	theme_minimal() +
 	geom_hline(yintercept = 5, linetype="longdash") +
 	geom_vline(xintercept = 95, linetype="longdash") +
 	scale_y_continuous(limits = c(0, 100)) +
 	scale_x_continuous(limits = c(0,100)) +
 	scale_fill_gradientn(limits=c(0,20),
 											 colors = c("#66C76B", "#F6D57C", "#F5736D"))
 
 ggplotly(p)
```


