---
title: "SamnSero QC Report"
date: "`r date()`"
output: 
  html_document:
    theme: cosmo
---

```{r setup, include=FALSE}
# global opts
knitr::opts_chunk$set(echo = F, message = F, warning = F)
```

```{r source}
library(magrittr)
library(scales)
library(jsonlite)
library(htmltools)
library(fontawesome)
library(plotly)
library(ggplot2)
library(reactable)
library(crosstalk)
source("src/reactable-helper.R")
```

```{r args}
# set test = 1 if running interactively
test=0

if (test != 0) {
	args <- c(getwd(),
						"../data/samnsero/checkm/checkm_summary.tsv",
						"../data/samnsero/quast_res_aggregate.tsv",
						"../data/samnsero/sistr_res_aggregate.csv",
						"../data/samnsero/kreport")
	src_dir <- dirname(knitr::current_input(dir = T))
} else {
	args <- commandArgs(trailingOnly = T)
	src_dir <- dirname(knitr::current_input(dir = T))
}

```

```{r main}
source(file.path(src_dir, "modules/qc/parse_args.R"))
source(file.path(src_dir, "workflow/qc_report_workflow.R"))
```

```{r plots}
bscols(
	cc_ly,
	quast_ly,
	widths = c(6,6)
)
```

## {.tabset}

### Serotyping Results

```{r sistr-table}
bscols(
	sistr_tbl,
	tagList(
				tags$button(tagList(fontawesome::fa("download"), "Download as CSV"),
										onclick = "Reactable.downloadDataCSV('sistr-table', 'SamnSero_sistr_res.csv')"),
				tags$button(tagList(fontawesome::fa("filter"), "Clear Filters"),
										onclick = "Reactable.setAllFilters('sistr-table', [])")
				),
	
	widths = c(12, 12)
)
```

### Assembly Statistics

```{r stats-table}
bscols(
	tagList(
		muiDependency(),
		stats_tbl),
	tagList(
				tags$button(tagList(fontawesome::fa("download"), "Download as CSV"),
  						onclick = "Reactable.downloadDataCSV('stats-table', 'SamnSero_assembly_stats.csv')"),
				tags$button(tagList(fontawesome::fa("filter"), "Clear Filters"),
										onclick = "Reactable.setAllFilters('stats-table', [])")),
	widths = c(12, 6)
)
```

### Taxonomy Summary

```{r kreport-summary-table}
bscols(
	tagList(
		muiDependency(),
		kreport_summary_tbl),
	tagList(
				tags$button(tagList(fontawesome::fa("download"), "Download as CSV"),
  						onclick = "Reactable.downloadDataCSV('kreport-summary-table', 'SamnSero_tax_summary.csv')"),
				tags$button(tagList(fontawesome::fa("filter"), "Clear Filters"),
										onclick = "Reactable.setAllFilters('kreport-summary-table', [])")),
	widths = c(12, 6)
)
```

### Classification Results

```{r kreport-class-table}
bscols(
	tagList(
		kreport_class_tbl),
	tagList(
				tags$button(tagList(fontawesome::fa("download"), "Download as CSV"),
  						onclick = "Reactable.downloadDataCSV('kreport-class-table', 'SamnSero_tax_class_res.csv')")
				),
	widths = c(12, 6)
)
```

## {-}

```{css}
.tag {
  display: inline-block;
  padding: 2px 12px;
  border-radius: 15px;
  font-weight: 600;
  font-size: 16px;
}

.status-PASS {
  background: hsl(123, 46.4%, 59%);
  color: hsl(123, 30%, 25%);
}

.status-WARNING {
  background: hsl(44, 87.1%, 72.5%);
  color: hsl(44, 45%, 30%);
}

.status-FAIL {
  background: hsl(3, 87.2%, 69.4%);
  color: hsl(3, 45%, 30%);
}

div.main-container {
  max-width: 1200px !important;
}
```

```{js}
// JavaScript code for the Material UI range filter. This is a js language
// chunk, but you could also inline this in R using `tags$script(HTML("..."))`

const muiRangeFilter = (column, state) => {
  // Get min and max values from raw table data and memoize so it doesn't
  // have to be recalculated each time
  const range = React.useMemo(() => {
    let min = Infinity
    let max = -Infinity
    state.data.forEach(row => {
      const value = row[column.id]
      if (value < min) {
        min = Math.floor(value)
      } else if (value > max) {
        max = Math.ceil(value)
      }
    })
    return [min, max]
  }, [state.data])

  const value = column.filterValue ? column.filterValue : range
  const valueLabel = `[${value[0]}, ${value[1]}]`

  return React.createElement(
    'div',
    // Add some margin so the tooltips don't get cut off
    { style: { margin: '0 8px' } },
    [
      valueLabel,
      React.createElement(
        MaterialUI.Slider,
        {
          value: value,
          min: range[0],
          max: range[1],
          step: 0.1,
          valueLabelDisplay: 'auto',
          onChange: (e, val) => column.setFilter(val),
          'aria-label': `Filter ${column.name}`
        }
      )
    ]
  )
}

const filterRange = (rows, columnId, filterValue) => {
  const [min, max] = filterValue
  return rows.filter(row => {
    const value = row.values[columnId]
    return value >= min && value <= max
  })
}
```
